### ISSUE TITLE
How to use the theme in hexo?

### ISSUE THREAD

**Issue by HDsky** [giuem/hexo-theme-iris#1]
自己摸索了半天，实在是不成功QAQ

**Comment by giuem** [comment]
你需要创建 _config.yml，然后根据需要修改配置

```
cp _config.example.yml _config.yml
```

**Comment by HDsky** [comment]
但还是不行🤣，晚一点我贴错误信息上来🤔

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
