### ISSUE TITLE
关于Markdown的代码块

### ISSUE THREAD

**Issue by KomoreKalu** [giuem/hexo-theme-iris#12]
`就是这个`
官方说法是 `Inline code`
在  [在 Linux 上搭建一个求生之路 2 服务器](https://www.giuem.com/setup-l4d2-server-for-linux/)里
![2020-06-30 06-45-27 的屏幕截图.png](https://i.loli.net/2020/06/30/S83NkdaEoiJ6DRv.png)
以及我自己的博客
![2020-06-30 06-48-16 的屏幕截图.png](https://i.loli.net/2020/06/30/GK7iRogl5fz2EM4.png)
都不能正常显示
应该不是没配置好 

希望能添加/修复这个功能  拜托了

**Comment by giuem** [comment]
样式就是这样的。。
