### ISSUE TITLE
能否在文章页面中的一侧加入导航栏？

### ISSUE THREAD

**Issue by HDsky** [giuem/hexo-theme-iris#8]
在看一些比较长的文章的时候，有导航栏可以方便的跳转到文章的关键部分。

**Comment by giuem** [comment]
你是说 toc

**Comment by HDsky** [comment]
嗯嗯

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by giuem** [comment]
Done.

如果要启用，参考[这里](https://github.com/giuem/hexo-theme-iris/commit/c41b9b7278ec75bd1bc9b6d5b267ac1681a997c9#diff-6003ab770be46047697ccce69dc87bff)修改主题配置文件。

**Comment by HDsky** [comment]
好的，感谢～
不过想问一下有DEMO么（
